[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "flask>=3.1.0",
    "flask-socketio>=5.4.1",
    "pdfplumber>=0.11.4",
    "requests>=2.32.3",
]
